### ISSUE TITLE
Uncaught TypeError: simplexml_load_string() expects parameter 1 to be string, boolean given

### ISSUE THREAD

**Issue by obccgn** [jknipper/fritzbox-aha#3]
I have tried to set up example file.

Server throws an error 

Uncaught TypeError: simplexml_load_string() expects parameter 1 to be string, boolean given

Is it actually possible to use myfritz.net hostname and port 47784 to get access to Fritz box from remote server?

Thanks.

**Comment by jknipper** [comment]
You can specify host, port and username like this:
```
$aha->login("xyzxyz.myfritz.net:47784", "username", "password", true, false);
```
